version: 0.2

phases:
  pre_build:
    commands:
      - echo HELP
      - sudo apt-get update
      - sudo apt-get upgrade
      - sudo apt-get install aws-cli
      - sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 250370816065.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t accad5/assessment .
      - docker tag accad5/assessment:latest 250370816065.dkr.ecr.ap-southeast-1.amazonaws.com/accad5/assessment:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 250370816065.dkr.ecr.ap-southeast-1.amazonaws.com/accad5/assessment:latest

artifacts:
  files:
    - "**/*"
  discard-paths: yes
